### Get all users
GET http://localhost:8080/api/users

### Add new user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "Roman",
  "lastName": "Kowalski",
  "email": "roman.kowalski@example.com",
  "password": "mojetajnehaslo",
  "pesel": "80010112345"
}

### Get all accounts
GET http://localhost:8080/api/accounts

### Get users accounts
GET http://localhost:8080/api/accounts/user/1

### Add new account
POST http://localhost:8080/api/accounts/user/4
Content-Type: application/json

{
    "accountNumber": "PL00000000000000000000000001",
    "balance": 100.50,
    "currency": "USD"
}

### Transfer money from account
POST http://localhost:8080/api/accounts/transfer
Content-Type: application/json

{
  "accountId": 9,
  "receiverAccountNumber": "PL00000000000000000000000002",
  "title": "Food",
  "amount": 10.00
}

### Delete account
DELETE http://localhost:8080/api/accounts/5

### Get all transactions
GET http://localhost:8080/api/transactions
Content-Type: application/json