spring.application.name=finance-api

spring.datasource.url=jdbc:postgresql://localhost:5432/finance-api_database
spring.datasource.username=bank_admin
spring.datasource.password=haslo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.file.name=logs/finance-api.log
logging.level.com.financeapi=DEBUG

# application.properties
bank.currency.sender-currency-fee-multiplyer=0.05